name: yeoda
channels:
  - conda-forge
dependencies:
  - python=3.6
  - regex
  - netCDF4
  - geopandas
  - xarray
  - matplotlib
  - dask
  - pip:
    - pytileproj==0.0.12
    - Equi7Grid==0.0.9
    - pyraster==0.1.6
    - git+https://github.com/TUW-GEO/geopathfinder.git@bmon # can be replaced in the future with geopathfinder==0.0.5