name: yeoda
channels:
  - conda-forge
dependencies:
  - python=3.6
  - gdal=2.4.3
  - cftime<1.1
  - geopandas
  - regex
  - netCDF4
  - xarray
  - dask
  - pip
  - pip:
    - pytileproj==0.0.12
    - Equi7Grid==0.0.10
    - veranda==0.1.0
    - geopathfinder==0.0.7